name: Unit Test

on:
  pull_request:
    branches:
      - main
    types: 
      - ready_for_review
      - review_requested

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          poetry install
      
      - name: Activate virtualenv
        run: poetry shell
      
      - name: Run tests
        run: poetry run pytest
